export const PERMISSIONS = [
  'VESSEL_CREATE',
  'VESSEL_EDIT',
  'VESSEL_VIEW',
  'VESSEL_DELETE',
  'WORK_ORDER_CREATE',
  'WORK_ORDER_EDIT',
  'WORK_ORDER_ASSIGN',
  'WORK_ORDER_APPROVE',
  'WORK_ORDER_VIEW',
  'WORK_ORDER_DELETE',
  'INSPECTION_CREATE',
  'INSPECTION_EDIT',
  'INSPECTION_APPROVE',
  'INSPECTION_VIEW',
  'REPORT_GENERATE',
  'REPORT_VIEW',
  'USER_MANAGE',
  'USER_INVITE',
  'AUDIT_VIEW',
  'ADMIN_FULL_ACCESS',
] as const;

export type Permission = typeof PERMISSIONS[number];

export const ROLES = {
  ECOSYSTEM_ADMIN: 'Ecosystem Admin',
  ORGANISATION_ADMIN: 'Organisation Admin',
  MANAGER: 'Manager',
  OPERATOR: 'Operator',
  VIEWER: 'Viewer',
} as const;

export type UserRole = keyof typeof ROLES;

export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, Permission[]> = {
  ECOSYSTEM_ADMIN: ['ADMIN_FULL_ACCESS'],
  ORGANISATION_ADMIN: [
    'VESSEL_CREATE', 'VESSEL_EDIT', 'VESSEL_VIEW', 'VESSEL_DELETE',
    'WORK_ORDER_CREATE', 'WORK_ORDER_EDIT', 'WORK_ORDER_ASSIGN', 'WORK_ORDER_APPROVE', 'WORK_ORDER_VIEW', 'WORK_ORDER_DELETE',
    'INSPECTION_CREATE', 'INSPECTION_EDIT', 'INSPECTION_APPROVE', 'INSPECTION_VIEW',
    'REPORT_GENERATE', 'REPORT_VIEW',
    'USER_MANAGE', 'USER_INVITE',
    'AUDIT_VIEW',
  ],
  MANAGER: [
    'VESSEL_VIEW', 'VESSEL_EDIT',
    'WORK_ORDER_CREATE', 'WORK_ORDER_EDIT', 'WORK_ORDER_ASSIGN', 'WORK_ORDER_APPROVE', 'WORK_ORDER_VIEW',
    'INSPECTION_CREATE', 'INSPECTION_EDIT', 'INSPECTION_APPROVE', 'INSPECTION_VIEW',
    'REPORT_GENERATE', 'REPORT_VIEW',
    'USER_INVITE',
  ],
  OPERATOR: [
    'VESSEL_VIEW',
    'WORK_ORDER_VIEW',
    'INSPECTION_CREATE', 'INSPECTION_EDIT', 'INSPECTION_VIEW',
    'REPORT_VIEW',
  ],
  VIEWER: [
    'VESSEL_VIEW',
    'WORK_ORDER_VIEW',
    'INSPECTION_VIEW',
    'REPORT_VIEW',
  ],
};
